FABRICS = {
 "cotton": {"properties":{"breathability":"High","absorbency":"High","heat_sensitivity":"Medium","shrinkage_risk":"Medium","color_fading_risk":"Medium"},"wash":{"cycle":"Normal or gentle","temperature":"30°C","detergent":"Mild standard detergent","spin":"800 RPM"},"dry":"Air dry where practical","iron":"Medium heat; steam optional","bleach":"Limited — test colourfastness","risks":{"heat":"Medium","mechanical":"Low","shrinkage":"Medium","fading":"Medium","fiber":"Low"}},
 "polyester": {"properties":{"breathability":"Low","absorbency":"Low","heat_sensitivity":"High","shrinkage_risk":"Low","color_fading_risk":"Low"},"wash":{"cycle":"Gentle","temperature":"30°C","detergent":"Mild liquid detergent","spin":"800 RPM"},"dry":"Air dry or tumble dry low heat","iron":"Low heat; use pressing cloth","bleach":"Avoid chlorine bleach","risks":{"heat":"High","mechanical":"Low","shrinkage":"Low","fading":"Low","fiber":"Medium"}},
 "denim": {"properties":{"breathability":"Medium","absorbency":"High","heat_sensitivity":"Medium","shrinkage_risk":"Medium","color_fading_risk":"High"},"wash":{"cycle":"Gentle, inside out","temperature":"Cold (30°C max)","detergent":"Mild detergent","spin":"800 RPM"},"dry":"Air dry; avoid prolonged high heat","iron":"Medium heat","bleach":"Avoid","risks":{"heat":"Medium","mechanical":"Medium","shrinkage":"Medium","fading":"High","fiber":"Low"}},
 "wool": {"properties":{"breathability":"High","absorbency":"High","heat_sensitivity":"High","shrinkage_risk":"High","color_fading_risk":"Medium"},"wash":{"cycle":"Wool/hand-wash","temperature":"Cold","detergent":"Wool-safe detergent","spin":"Low or none"},"dry":"Dry flat, reshape while damp","iron":"Low heat with cloth","bleach":"Avoid","risks":{"heat":"High","mechanical":"High","shrinkage":"High","fading":"Medium","fiber":"High"}},
 "silk": {"properties":{"breathability":"High","absorbency":"Medium","heat_sensitivity":"High","shrinkage_risk":"Medium","color_fading_risk":"High"},"wash":{"cycle":"Hand-wash/gentle","temperature":"Cold","detergent":"Silk-safe mild detergent","spin":"Low or none"},"dry":"Air dry away from direct sun","iron":"Low heat, inside out","bleach":"Avoid","risks":{"heat":"High","mechanical":"High","shrinkage":"Medium","fading":"High","fiber":"High"}}
}

def recommendation(fabric: str):
    item = FABRICS[fabric]
    return {**item, "explanation": f"{item['wash']['temperature']} and {item['wash']['cycle'].lower()} care are suggested from the documented {fabric} properties and risk rules.", "eco": ["Wash full loads where suitable.", "Use the lowest temperature compatible with the care label.", "Air dry when practical."], "eco_score_method": "Project-defined score: 40 temperature + 35 drying method + 25 cycle intensity; shown only after a verified recommendation."}
